### ISSUE TITLE
java.lang.UnsatisfiedLinkError: Error looking up function 'utimensat'

### ISSUE THREAD

**Issue by eed3si9n** [sbt/io#95]
## steps

Run tests on macos.

## problem

```
[info] sbt.io.PathMapperSpec *** ABORTED ***
[info]   java.lang.UnsatisfiedLinkError: Error looking up function 'utimensat': dlsym(0x10b6cde70, utimensat): symbol not found
[info]   at com.sun.jna.Function.<init>(Function.java:245)
[info]   at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:566)
[info]   at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:542)
[info]   at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:528)
[info]   at com.sun.jna.Library$Handler.invoke(Library.java:228)
[info]   at com.sun.proxy.$Proxy13.utimensat(Unknown Source)
[info]   at sbt.internal.io.PosixMilliLong.$anonfun$setModifiedTimeNative$1(Milli.scala:117)
[info]   at sbt.internal.io.PosixMilli.checkedIO(Milli.scala:99)
[info]   at sbt.internal.io.PosixMilliLong.setModifiedTimeNative(Milli.scala:117)
[info]   at sbt.internal.io.PosixMilliLong.setModifiedTimeNative(Milli.scala:110)
```

/cc @cunei

**Comment by eed3si9n** [comment]
Maybe we should use `utimes`? http://man7.org/linux/man-pages/man2/utime.2.html

**Comment by eed3si9n** [comment]
I can't run locally baked sbt without `-Dsbt.io.jdktimestamps=true`

**Comment by cunei** [comment]
There are a number of timestamp-related calls, introduced at various times in the BSD/POSIX history. Among them: `utime`, `utimes`, `lutimes`, `futimes`, `utimens`, `futimens`, `utimensat`, `futimensat`, `fdutimensat`, plus other system-specific ones.

The "utime" variants use a simple `time_t`, and deal with whole seconds. The "utime**s**" variants use `struct timeval`, with seconds and microseconds. The most recent, and preferable, are the "utime**ns**" variants, which have a nanosecond precision. The drawback of "utimes", besides the lower precision", is that it can only set simultaneously modification time and access time. It means that changing only the modification time requires going through an extra `stat` call in order to extract the current access time, so that the same, plus the updated modification time, can be set again by "utimes". In general, the "utime**ns**" calls are the most up-to-date interface, and are preferable. 

It turns out that `utimensat` is available in High Sierra, but not on Sierra or previous versions. That is a bit shocking since `utimensat` was standardized in 2008, in IEEE Std 1003.1-2008 (POSIX.1), a good 10 years ago.

I will add further checks so that OSX uses `utimensat` if available, and falls back to `utimes` otherwise.

**Comment by dwijnand** [comment]
Fixed with https://github.com/sbt/io/pull/100.
